### ISSUE TITLE
Update LinkedList Page

### ISSUE THREAD

**Issue by Shawful** [choskim/data-structures#1]
Would you mind updating the code on the following page?  And link it to this repo?  I think it could help people to look at the github code.  I've noticed that the code on the webpage linked below is out of date and does not correctly implement a linked list.

Incorrect implementation of Linked List
http://www.choskim.me/linked-list/

I'm sure this will help people!

Thanks,

Shawn

**Comment by choskim** [comment]
@Shawful, thanks for submitting an issue. I believe you'll find your answers in the following information:
- My blog contains an outdated and inaccurate implementation of Linked List and Set. I wrote both during a writing binge with an intention of revision. These intended--and long overdue--revisions will happen after I complete a migration of my blog from Ghost and Azure to Jekyll/Polymer and Github Pages. The timeline of my migration is ~2 weeks. The updates will take a bit longer.

My blog post on Linked List will eventually contain a link that redirects users to Tuts+. Several months ago, I made an arrangement with Tuts+ to publish my series on Data Structures with JavaScript. The publication dates are from September 3rd to September 24th. The article on Singly Linked List (and Doubly Linked List) will be published on September 17th. 

I hope this information helps.
